---
- name: Install Ubuntu Software Settings
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - software-properties-common
      - python3-apt

- name: Add certbot repository
  become: true
  apt_repository:
    repo: ppa:certbot/certbot
    state: present

- name: Install certbot
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
      packages:
        - certbot
        - python-certbot

- name: Configure Lets Encrypt renew cron job
  become: true
  cron:
    name: Renew Lets Encrypt certificates
    weekday: 0
    job: certbot renew
